### ISSUE TITLE
asyncComponent 方法无法获取 import

### ISSUE THREAD

**Issue by jkhmnk** [hyy1115/react-echarts-modules#2]
const PieReact = asyncComponent(() => import(/* webpackChunkName: "PieReact" */'./EchartsDemo/PieReact'))  //饼图组件

这一句代码 里，asyncComponent方法返回是空的，我仔细查过。 import 组件返回的是空的。

是否是还要webpack配置的？ 
/* webpackChunkName: "PieReact" */     看到有这一句话。  怀疑是要在webpack里配置好 这样才能找得到。

**Comment by hyy1115** [comment]
webpackChunkName可以不需要，检查package.json的插件版本号是否有问题
