### ISSUE TITLE
candlestick 配置文件里是不是存在一些问题 ?

### ISSUE THREAD

**Issue by codthing** [hyy1115/react-echarts-modules#5]
我在本地复用了作者的作品, 但是会经常性的出现`Error: Component series.line not exists. Load it first.`这个错误, 提示中有提到这个 K线图的初始化有点问题 , 请问这个bug 如何解决 ?

错误断点 1.

` componentDidMount() {
> 31 |   this.initPie()
     | ^  32 | }`

错误断点 2. 

` .then((Component) => {
> 19 |   this.setState({ Component });
     | ^  20 | })`

**Comment by hyy1115** [comment]
可以参考下其他人遇到这种情况的解决方案 [series.line not exists](https://github.com/ecomfe/vue-echarts/issues/72#issuecomment-362279845)

错误是指line不存在，可能没有在k线图组件引入line组件，而实际使用到了line组件。

AsyncComponent是比较久之前写的一个异步加载插件，在github搜一个比较新、比较多人使用的，可以减少一些bug出现。

**Comment by mofengfs** [comment]
> 可以参考下其他人遇到这种情况的解决方案 [series.line not exists](https://github.com/ecomfe/vue-echarts/issues/72#issuecomment-362279845)
> 
> 错误是指line不存在，可能没有在k线图组件引入line组件，而实际使用到了line组件。
> 
> AsyncComponent是比较久之前写的一个异步加载插件，在github搜一个比较新、比较多人使用的，可以减少一些bug出现。

xie

**Comment by mofengfs** [comment]
@hyy1115

**Comment by codthing** [comment]
@hyy1115 谢谢
